---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      timezone: "Europe/Amsterdam"
      interval: daily
      time: "02:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      timezone: "Europe/Amsterdam"
      interval: daily
      time: "02:00"
